trainer_type: "plain"
trainer: 
  epochs: 20
  dataset: "cifar"
  train_batch_szie: 128
  test_batch_size: 128
  model: "vgg"
  optimizer_type: "SGD"
  optimizer: 
    lr: 0.1
    momentum: 0.9
    weight_decay: 5.e-4
  lr_schedule:
    start: 0.1
    boundaries: [5,10]
    rate: 0.1

