trainer_type: "da"
trainer: 
    epochs: 20
    dataset: "digits"
    source: "s"
    target: "m"
    label_batch_size: 128
    train_batch_size: 256
    test_batch_size: 256
    model: "convnet"
    th: 0.8
    ratio: 1
    warmup_epochs: 0
    teacher_alpha: 0.9921875
    optimizer_type: "SGD"
    stu_optimizer: 
        lr: 0.05
        momentum: 0.9
        weight_decay: 4.e-5
    lr_schedule:
        start: 0.05
        boundaries: [5,10]
        rate: 0.05
 


