trainer_type: "semi"
trainer:
    epochs: 60
    dataset: "cifar"
    numlabel: 4000
    label_batch_size: 128
    train_batch_size: 256
    test_batch_size: 256
    # label_batch_size: 128
    # train_batch_size: 256
    # test_batch_size: 256

    model: "convnet"
    th: 0.75
    ratio: 0.3
    warmup_epochs: 0
    teacher_alpha: 0.9921875
    optimizer_type: "SGD"
    stu_optimizer: 
        lr: 0.1
        momentum: 0.9
        weight_decay: 5.e-4
    lr_schedule:
        start: 0.1
        boundaries: [20,40]
        rate: 0.1
    save: False
 


